# Generated by Django 2.1.4 on 2019-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('subregion', models.CharField(blank=True, max_length=200, null=True)),
                ('variety', models.CharField(blank=True, max_length=200, null=True)),
                ('winery', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
