# Generated by Django 2.0.6 on 2018-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('designation', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('subregion', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('winery', models.CharField(max_length=200)),
            ],
        ),
    ]
