# Generated by Django 2.1 on 2018-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('Alamo', 'Alamo'), ('Capistrano', 'capistrano'), ('San Jose', 'San Jose'), ('Espada', 'Espada'), ('Terrace', 'Terrace')], max_length=20)),
                ('reservation_date', models.DateField()),
                ('purpose', models.TextField(max_length=1000)),
                ('special_request', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=6)),
                ('name_on_card', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
