# Generated by Django 2.1 on 2018-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking_info',
            field=models.OneToOneField(default=1, on_delete='CASCADE', to='restaurant.BookingInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_info',
            field=models.OneToOneField(default=1, on_delete='CASCADE', to='restaurant.PaymentInformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='room',
            field=models.CharField(choices=[('Alamo', 'Alamo'), ('Capistrano', 'Capistrano'), ('San Jose', 'San Jose'), ('Espada', 'Espada'), ('Terrace', 'Terrace')], max_length=20),
        ),
    ]
