# Generated by Django 2.1 on 2018-09-02 21:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180902_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginformation',
            name='additional_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('food', 'food'), ('flowers', 'flowers'), ('candels', 'candels'), ('valet perking', 'valet parking')], max_length=34, null=True),
        ),
    ]
